#!/bin/bash
# Install required packages
sudo apt update
sudo apt install -y hostapd dnsmasq
sudo pip3 install waveshare-epaper --break-system-packages
# Stop services temporarily
# sudo systemctl stop hostapd
# sudo systemctl stop dnsmasq

# Create fallback script
# sudo tee /usr/local/bin/wifi-fallback.sh > /dev/null << 'EOL'




sudo apt update
sudo apt install -y hostapd dnsmasq
sudo pip3 install waveshare-epaper --break-system-packages

sudo raspi-config nonint do_spi 0
#create scripts 
# copy start of python 
sudo cp rc.local /etc/
sudo chmod +x /etc/rc.local
# add r.service for wifi connection
sudo cp r.service /etc/systemd/system/
sudo systemctl daemon-reexec
sudo systemctl daemon-reload
sudo systemctl enable r.service
sudo systemctl start r.service

systemctl status r.service


# add chronodot 


